hostbill:
  credentials:
    api_id: id
    api_key: key
  domain: domain.com
zoho:
  credentials:
    refresh_token: token
    client_id: id
    client_secret: secret
bugsnag:
  credentials:
    api_key: key